sudo: required

services:
  - docker

script:
  - docker build -t promact/node-docker .
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push promact/node-docker
